version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "03:00"
      timezone: "Asia/Seoul"
    labels:
      - ":game_die: dependencies"
      - ":robot: bot"
  - package-ecosystem: "docker"
    directory: "/.docker"
    schedule:
      interval: "daily"
      time: "03:00"
      timezone: "Asia/Seoul"
    labels:
      - ":game_die: dependencies"
      - ":robot: bot"
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly
