services:
  workspace:
    build:
      context: .
      dockerfile: .docker/Dockerfile.ubuntu
      args:
        ARG_BUILD_FROM: $BUILD_FROM
        ARG_USERNAME: $CONTAINER_USERNAME
        ARG_USER_UID: $CONTAINER_USER_UID
        ARG_USER_GID: $CONTAINER_USER_GID
        ARG_WORKSPACE_ROOT: $CONTAINER_WORKSPACE_ROOT
        ARG_USER_FULLNAME: $CONTAINER_USER_FULLNAME
        ARG_USER_EMAIL: $CONTAINER_USER_EMAIL
        ARG_GITHUB_USERNAME: $GITHUB_USERNAME
        ARG_SYSTEM_HOSTNAME: $CONTAINER_HOSTNAME
        ARG_WORKSPACE_LOCATION: $CONTAINER_WORKSPACE_LOCATION
        ARG_DOTFILES_VERSION: $DOTFILES_VERSION
        ARG_APP_INSTALL_ROOT: $APP_INSTALL_ROOT
        ARG_APP_DIRNAME: $APP_DIRNAME
        ARG_CONTAINER_SERVICE_NAME: $CONTAINER_SERVICE_NAME
    image: $IMAGE_NAME:$IMAGE_TAG
    hostname: $CONTAINER_HOSTNAME
    restart: always
    command:
      - bash
      - $CONTAINER_LAUNCH_SCRIPT
    environment:
      USER_UID: $CONTAINER_USER_UID
      USER_GID: $CONTAINER_USER_GID
      USER_FULLNAME: $CONTAINER_USER_FULLNAME
      USER_EMAIL: $CONTAINER_USER_EMAIL
      GITHUB_USERNAME: $CONTAINER_GITHUB_USERNAME
      WORKSPACE_LOCATION: $CONTAINER_WORKSPACE_LOCATION
      SYSTEM_HOSTNAME: $CONTAINER_HOSTNAME
      GIT_COMMIT_GPGSIGN: $GIT_COMMIT_GPGSIGN
      WORKSPACE_ROOT: $CONTAINER_WORKSPACE_ROOT
      IMAGE_VARIANT: $IMAGE_VARIANT
      JUPYTER_PORT: $CONTAINER_JUPYTER_PORT
      JUPYTER_TOKEN: $CONTAINER_JUPYTER_TOKEN
    ulimits:
      stack: 67108864
      memlock: -1
    ipc: $CONTAINER_IPC
    ports:
      - "$HOST_SSH_PORT:$CONTAINER_SSH_PORT"
      - "$HOST_JUPYTER_PORT:$CONTAINER_JUPYTER_PORT"
      - "$HOST_WEB_SVC_PORT:$CONTAINER_WEB_SVC_PORT"
    volumes:
      - "$HOST_SCRIPTS_DIR:$CONTAINER_WORKSPACE_ROOT/scripts"
      - "$HOST_HF_HOME:$CONTAINER_HF_HOME"
      - "$HOST_WORKSPACE_ROOT:$CONTAINER_WORKSPACE_ROOT"
      - "$HOST_CACHE_DIR:$CONTAINER_CACHE_DIR"
      - "$HOST_SSH_DIR:$CONTAINER_SSH_DIR"
      - "$HOST_GH_CONFIG_DIR:$CONTAINER_GH_CONFIG_DIR"
      - "$HOST_PASSAGE_DIR:$CONTAINER_PASSAGE_DIR"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["${CONTAINER_CUDA_DEVICE_ID}"]
              capabilities: [gpu]
networks:
  default:
    name: $CONTAINER_NETWORK_NAME
    external: true
