---
name: semantic-release

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - release*
    paths:
      - ".docker/**"

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  build:
    # Name the Job
    name: semantic-release
    # Set the agent to run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11"]

    # Load all steps #
    steps:
      # Checkout the code base #
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # set env variable
      - name: Set env variable
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      # install uv
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}

      # install dependencies
      - name: Install dependencies
        run: uv sync

      - name: Python Semantic Release
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          uv run semantic-release publish --verbosity=DEBUG --define=branch=${{ env.BRANCH }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
